#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    middleLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl7,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_mm)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_6,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_7,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_8,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightDrive,    tmotorVex393_HBridge, openLoop, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port2,           clawMotor,     tmotorVex393_MC29, openLoop, encoderPort, I2C_6)
#pragma config(Motor,  port3,           leftDrive,     tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port4,           clawExtender,  tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port5,           clawArm,       tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port6,           clawWrist,     tmotorVex393_MC29, openLoop, encoderPort, I2C_7)
#pragma config(Motor,  port7,           launchArm,     tmotorVex393_MC29, openLoop, encoderPort, I2C_5)
#pragma config(Motor,  port8,           leftIntake,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightIntake,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          loadMotor,     tmotorVex393_HBridge, openLoop, encoderPort, I2C_8)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// IMEs 4 and 6 do not actually exist
// Neither does the gyro

#include "SensorFunctions.c"
#include "MiscFunctions.c"

// 90 degree turn is -557, 557

task main()
{
	init();
	while (true) {
		loopCode();
		switch (step) {
			case 0:
				if (moveBaseTo(700, 700) < 15)
					clearStep();
				break;
			case 1:
				if (moveBaseTo(-557, 557) < 15)
					clearStep();
				break;
			case 2:
				if (wait(50) == 0)
					clearStep();
				break;
			case 3:
				if (moveBaseTo(-800, -800) < 15)
					clearStep();
				break;
			case 4:
				if (moveClawArmTo(293) < 15)
					clearStep();
				break;
			case 5:
				if (moveLaunchArmTo(220) < 15)
					clearStep();
				break;
			case 6:
				moveIntake(-127);
				if (wait(100) == 0)
					clearStep();
				break;
			case 7:
				moveLaunchArmTo(21);
				if (moveClawArmTo(21) < 15)
					clearStep();
				break;
			case 8:
				if (moveBaseTo(0, -900) < 15)
					clearStep();
				break;
			case 9:
				moveIntake(127);
				moveLoad(127);
				if (moveBaseTo(400, 400) < 15)
					clearStep();
				break;
			case 10:
				if (moveBaseTo(-400, -400) < 15)
					clearStep();
				break;
			case 11:
				if (moveBaseTo(0, 950) < 15)
					clearStep();
				break;
			case 12:
				if (moveClawArmTo(229) < 15)
					clearStep();
				break;
			case 13:
				if (moveLaunchArmTo(179) < 15)
					clearStep();
				break;
			case 14:
				moveIntake(-127);
				moveLoad(-127);
				if (wait(500) == 0)
					clearStep();
				break;
			case 15:
				moveClawArmTo(0);
				moveLaunchArmTo(-20);
				moveClawWristTo(-600);
				if (moveBaseTo(850, -850) < 15)
					clearStep();
				break;
			case 16:
				moveClawExtender(127);
				if (wait(1000) == 0)
					clearStep();
				break;
			case 17:
				moveClaw(127);
				if (wait(500) == 0)
					clearStep();
				break;
			case 18:
				if (moveBaseTo(-800, 800) < 15)
					clearStep();
				break;
			/*case 15:
				moveLaunchArmTo(-20);
				moveClawArmTo(60)
				if (moveClawWristTo(-300) < 15)
					clearStep();
				break;
			case 16:
				if (moveBaseTo(2550, 2550) < 15)
					clearStep();
				break;*/
		}
	}
}
